export default Object.freeze({
  WELCOME: 'Welcome',
  REGISTER: 'Register',
  LOGIN: 'Login',
  SETUP: 'Setup',
  HOME: 'Home',
  NEW_POST: 'New Post',
  POST_DETAILS: 'Post Details',
  EDIT_POST: 'Edit Post',
  VIEW_PROFILE: 'View Profile',
  EDIT_PROFILE: 'Edit Profile',
  ALL_USERS: 'ALL_USERS',
  COMMENTS: 'Comments',
  RESET_PASSWORD: 'Reset Password',
  USER_PROFILE: 'User Profile',
  MY_FRIENDS: 'My Friends',
  CHAT: 'Chat',
});
